### ISSUE TITLE
Not all coins

### ISSUE THREAD

**Issue by AKprisonER** [blakelee/CoinProfits#3]
only top 100 coins are downloaded.. Other coins are not displaying.
I have some coins. That also not available

**Comment by AKprisonER** [comment]
````
@GET("ticker/")
    fun getCoins(
            @Query("limit") limit: Int? = null,
            @Query("convert") convert: String? = null
    ): Observable<JsonArray>

 @GET("ticker/{id}")
    fun getCoinById(
            @Path("id") id: String,
            @Query("convert") convert: String? = null
    ): Observable<JsonArray>
}
````

Needs to be reviewed

**Comment by AKprisonER** [comment]
Unorthodox fix is, by changing 
`@GET("ticker/?limit=200")` on line 15 ( CoinApi.kt )
 Now Coin limit is 200. Increasing the coin count makes app data size bigger with frequent crash.

**Comment by blakelee** [comment]
Go to settings and click redownload all currencies. New currencies that are added have to be downloaded. Unless coinmarketcap changed their api, it should get the new ones.
